package com.spd.qsevendemo.model;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.spd.qsevendemo.model.DataBean;
import com.spd.qsevendemo.model.SevenBean;

import com.spd.qsevendemo.model.DataBeanDao;
import com.spd.qsevendemo.model.SevenBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dataBeanDaoConfig;
    private final DaoConfig sevenBeanDaoConfig;

    private final DataBeanDao dataBeanDao;
    private final SevenBeanDao sevenBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dataBeanDaoConfig = daoConfigMap.get(DataBeanDao.class).clone();
        dataBeanDaoConfig.initIdentityScope(type);

        sevenBeanDaoConfig = daoConfigMap.get(SevenBeanDao.class).clone();
        sevenBeanDaoConfig.initIdentityScope(type);

        dataBeanDao = new DataBeanDao(dataBeanDaoConfig, this);
        sevenBeanDao = new SevenBeanDao(sevenBeanDaoConfig, this);

        registerDao(DataBean.class, dataBeanDao);
        registerDao(SevenBean.class, sevenBeanDao);
    }
    
    public void clear() {
        dataBeanDaoConfig.clearIdentityScope();
        sevenBeanDaoConfig.clearIdentityScope();
    }

    public DataBeanDao getDataBeanDao() {
        return dataBeanDao;
    }

    public SevenBeanDao getSevenBeanDao() {
        return sevenBeanDao;
    }

}
